;
; File generated by cc65 v 2.10.1
;
	.fopt		compiler,"cc65 v 2.10.1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank, tmp1, ptr1, ptr2
	.macpack	longbranch
	.import		_InstallVT03
	.import		_InitVT03System
	.import		_WaitSync
	.import		_ClearSprBuffer
	.import		_InitScreen
	.import		_ClearPaletteBuffer
	.import		_PatternUpdate
	.import		_WaitPatternUpdate
	.import		_EnableNMI
	.import		_DisableNMI
	.import		_OpenScreenDisplay
	.import		_CloseScreenDisplay
	.import		_SetVectors
	.import		_StandardNMI
	.import		_StandardIRQ
	.import		_MusicInitial
	.import		_MusicSetup
	.import		_MusicPlay
	.import		_MusicEffect
	.import		_Music_SquareEffect00
	.import		_Music_SquareEffect01
	.import		_Music_SquareEffect02
	.import		_Music_SquareEffect03
	.import		_Music_TriangleEffect00
	.import		_Music_TriangleEffect01
	.import		_Music_TriangleEffect02
	.import		_Music_NoiseEffect00
	.import		_Music_NoiseEffect01
	.import		_Music_NoiseEffect02
	.import		_Music_NoiseEffect03
	.import		_Music_NoiseEffect04
	.import		_Effect41
	.import		_Effect42
	.import		_Effect43
	.import		_Effect44
	.import		_Effect45
	.import		_Effect46
	.import		_Effect47
	.import		_Effect48
	.import		_Effect49
	.import		_irq
	.import		_nmi
	.import		_InitSystem
	.import		_InitPalette
	.import		_Outputxy
	.export		_BlackLine
	.import		_ReadJoystick1
	.import		_RunGame
	.export		_DisplayPage
	.import		_InitLCD
	.import		_InitSystemTestSprite
	.export		_CheckGameCount
	.import		_ReadJoystick2
	.import		_InitMenuSprite
	.import		_sprintf
	.export		_TempBuffer
	.import		_midi02
	.import		_GamesDefine
	.export		_Mus_SquareIndexTable
	.export		_Mus_TriangleIndexTable
	.export		_Mus_NoiseIndexTable
	.export		_Mus_DPCMIndexTable
	.export		_Music_IndexTable
	.import		_PICTable
	.import		_MusicLoop
	.export		_TestSystem
	.export		_main

.segment	"RODATA"

_BlackLine:
	.byte	$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20
	.byte	$20,$20,$20,$20,$20,$00
_Mus_SquareIndexTable:
	.addr	_Music_SquareEffect00
	.addr	_Music_SquareEffect01
	.addr	_Music_SquareEffect02
	.addr	_Music_SquareEffect03
_Mus_TriangleIndexTable:
	.addr	_Music_TriangleEffect00
	.addr	_Music_TriangleEffect01
	.addr	_Music_TriangleEffect02
_Mus_NoiseIndexTable:
	.addr	_Music_NoiseEffect00
	.addr	_Music_NoiseEffect01
	.addr	_Music_NoiseEffect02
	.addr	_Music_NoiseEffect03
	.addr	_Music_NoiseEffect04
_Mus_DPCMIndexTable:
	.word	$0000
_Music_IndexTable:
	.addr	_Mus_SquareIndexTable
	.addr	_Mus_SquareIndexTable
	.addr	_Mus_TriangleIndexTable
	.addr	_Mus_NoiseIndexTable
	.addr	_Mus_DPCMIndexTable
L0001:
	.byte	$4E,$39,$39,$20,$54,$45,$53,$54,$20,$50,$52,$4F,$47,$52,$41,$4D
	.byte	$00,$4E,$39,$39,$20,$54,$45,$53,$54,$20,$53,$52,$41,$4D,$20,$4F
	.byte	$4B,$00,$4E,$39,$39,$20,$54,$45,$53,$54,$20,$53,$52,$41,$4D,$20
	.byte	$45,$52,$52,$4F,$52,$00,$25,$64,$2E,$25,$73,$28,$25,$64,$29,$00
	.byte	$25,$64,$2E,$25,$73,$00

.segment	"BSS"

_TempBuffer:
	.res	32,$00

; ---------------------------------------------------------------
; void __near__ DisplayPage (int, int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DisplayPage: near

.segment	"CODE"

	ldy     #$3A
	jsr     subysp
	ldx     #$00
	lda     #$00
	ldy     #$38
	jsr     staxysp
L0135:	ldy     #$39
	jsr     ldaxysp
	jsr     pushax
	lda     #$11
	jsr     toslta0
	jne     L0138
	jmp     L0136
L0138:	ldy     #$3D
	jsr     ldaxysp
	jsr     pushax
	ldy     #$3B
	jsr     ldaxysp
	jsr     tosaddax
	jsr     pushax
	ldy     #$3D
	jsr     ldaxysp
	jsr     tosltax
	jeq     L013D
	ldy     #$3D
	jsr     ldaxysp
	jsr     pushax
	ldy     #$3B
	jsr     ldaxysp
	jsr     tosaddax
	jsr     aslax1
	clc
	adc     #<(_GamesDefine)
	tay
	txa
	adc     #>(_GamesDefine)
	tax
	tya
	ldy     #$02
	jsr     staxysp
	ldy     #$03
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	ldy     #$00
	jsr     staxysp
	ldy     #$01
	jsr     ldaxysp
	jsr     incax8
	ldy     #$04
	jsr     staxysp
	ldy     #$03
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     #$02
	jsr     tosgea0
	jeq     L0149
	lda     #$06
	jsr     leaasp
	jsr     pushax
	lda     #<(L0001+54)
	ldx     #>(L0001+54)
	jsr     pushax
	ldy     #$41
	jsr     ldaxysp
	jsr     pushax
	ldy     #$3F
	jsr     ldaxysp
	jsr     tosaddax
	jsr     incax1
	jsr     pushax
	ldy     #$0B
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0B
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldy     #$0A
	jsr     _sprintf
	jmp     L0151
L0149:	lda     #$06
	jsr     leaasp
	jsr     pushax
	lda     #<(L0001+64)
	ldx     #>(L0001+64)
	jsr     pushax
	ldy     #$41
	jsr     ldaxysp
	jsr     pushax
	ldy     #$3F
	jsr     ldaxysp
	jsr     tosaddax
	jsr     incax1
	jsr     pushax
	ldy     #$0B
	jsr     ldaxysp
	jsr     pushax
	ldy     #$08
	jsr     _sprintf
L0151:	ldx     #$00
	lda     #$00
	ldy     #$36
	jsr     staxysp
L0157:	ldy     #$37
	jsr     ldaxysp
	jsr     pushax
	lda     #$18
	jsr     toslta0
	jne     L015A
	jmp     L0158
L015A:	lda     #$06
	jsr     leaasp
	ldy     #$36
	clc
	adc     (sp),y
	pha
	txa
	iny
	adc     (sp),y
	tax
	pla
	ldy     #$00
	jsr     ldauidx
	cmp     #$00
	jsr     booleq
	jeq     L0159
	jmp     L0158
L0159:	ldy     #$37
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$36
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	jmp     L0157
L0158:	ldy     #$37
	jsr     ldaxysp
	jsr     pushax
	lda     #$18
	jsr     toslta0
	jne     L0165
	jmp     L0163
L0165:	lda     #$06
	jsr     leaasp
	ldy     #$36
	clc
	adc     (sp),y
	pha
	txa
	iny
	adc     (sp),y
	tax
	pla
	jsr     pushax
	ldx     #$00
	lda     #$20
	ldy     #$00
	jsr     staspidx
	ldy     #$37
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$36
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	jmp     L0158
L0163:	lda     #$06
	jsr     leaasp
	ldy     #$36
	clc
	adc     (sp),y
	pha
	txa
	iny
	adc     (sp),y
	tax
	pla
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staspidx
	ldx     #$00
	lda     #$05
	jsr     pushax
	ldy     #$3B
	jsr     ldaxysp
	jsr     incax7
	jsr     pushax
	lda     #$0A
	jsr     leaasp
	jsr     pushax
	jsr     _Outputxy
	jmp     L0137
L013D:	jmp     L0136
L0137:	ldy     #$39
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$38
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	jmp     L0135
L0136:	ldy     #$39
	jsr     ldaxysp
	cpx     #$00
	bne     L0176
	cmp     #$11
L0176:	jsr     boolne
	jeq     L0174
	ldx     #$00
	lda     #$04
	jsr     pushax
	ldy     #$3B
	jsr     ldaxysp
	jsr     incax7
	jsr     pushax
	lda     #<(_BlackLine)
	ldx     #>(_BlackLine)
	jsr     pushax
	jsr     _Outputxy
	ldy     #$39
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$38
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	jmp     L0136
L0174:	ldy     #$3E
	jsr     addysp
	rts

.endproc

; ---------------------------------------------------------------
; int __near__ CheckGameCount ()
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_CheckGameCount: near

.segment	"CODE"

	jsr     enter
	jsr     decsp2
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staxysp
L00B1:	ldy     #$01
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_GamesDefine)
	tay
	txa
	adc     #>(_GamesDefine)
	tax
	tya
	ldy     #$00
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	jeq     L00B2
	ldy     #$01
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$00
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	jmp     L00B1
L00B2:	ldy     #$01
	jsr     ldaxysp
	jmp     L00AE
L00AE:	ldy     #$02
	jsr     leavey
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ TestSystem ()
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_TestSystem: near

.segment	"CODE"

	jsr     enter
	jsr     decsp3
	ldy     #$00
	jsr     _MusicInitial
	ldy     #$00
	jsr     _InitSystemTestSprite
	ldx     #$00
	lda     #$08
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     pushax
	lda     #<(L0001)
	ldx     #>(L0001)
	jsr     pushax
	jsr     _Outputxy
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staxysp
L00BE:	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$20
	lda     #$00
	jsr     tosltax
	jne     L00C1
	jmp     L00BF
L00C1:	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$60
	lda     #$00
	jsr     tosaddax
	jsr     pushax
	ldx     #$00
	lda     #$55
	ldy     #$00
	jsr     staspidx
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$60
	lda     #$00
	jsr     tosaddax
	ldy     #$00
	jsr     ldauidx
	cmp     #$55
	jsr     boolne
	jeq     L00CA
	jmp     L00BF
L00CA:	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$60
	lda     #$00
	jsr     tosaddax
	jsr     pushax
	ldx     #$00
	lda     #$AA
	ldy     #$00
	jsr     staspidx
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$60
	lda     #$00
	jsr     tosaddax
	ldy     #$00
	jsr     ldauidx
	cmp     #$AA
	jsr     boolne
	jeq     L00C0
	jmp     L00BF
L00C0:	ldy     #$00
	ldx     #$00
	lda     #$11
	jsr     addeqysp
	jmp     L00BE
L00BF:	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$20
	lda     #$00
	jsr     tosgeax
	jeq     L00D3
	ldx     #$00
	lda     #$08
	jsr     pushax
	ldx     #$00
	lda     #$0B
	jsr     pushax
	lda     #<(L0001+17)
	ldx     #>(L0001+17)
	jsr     pushax
	jsr     _Outputxy
	jmp     L00D9
L00D3:	ldx     #$00
	lda     #$08
	jsr     pushax
	ldx     #$00
	lda     #$0B
	jsr     pushax
	lda     #<(L0001+34)
	ldx     #>(L0001+34)
	jsr     pushax
	jsr     _Outputxy
L00D9:	ldy     #$00
	jsr     _WaitSync
	ldy     #$00
	jsr     _ReadJoystick2
	ldy     #$02
	sta     (sp),y
	ldy     #$00
	jsr     _InitSystemTestSprite
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	ldx     #$00
	and     #$08
	stx     tmp1
	ora     tmp1
	jeq     L00E5
	ldx     #$00
	lda     #$5F
	sta     $0201
L00E5:	ldy     #$02
	ldx     #$00
	lda     (sp),y
	ldx     #$00
	and     #$04
	stx     tmp1
	ora     tmp1
	jeq     L00EA
	ldx     #$00
	lda     #$5F
	sta     $0205
L00EA:	ldy     #$02
	ldx     #$00
	lda     (sp),y
	ldx     #$00
	and     #$02
	stx     tmp1
	ora     tmp1
	jeq     L00EF
	ldx     #$00
	lda     #$5F
	sta     $0209
L00EF:	ldy     #$02
	ldx     #$00
	lda     (sp),y
	ldx     #$00
	and     #$01
	stx     tmp1
	ora     tmp1
	jeq     L00F4
	ldx     #$00
	lda     #$5F
	sta     $020D
L00F4:	ldy     #$02
	ldx     #$00
	lda     (sp),y
	ldx     #$00
	and     #$20
	stx     tmp1
	ora     tmp1
	jeq     L00F9
	ldx     #$00
	lda     #$5F
	sta     $0211
L00F9:	ldy     #$02
	ldx     #$00
	lda     (sp),y
	ldx     #$00
	and     #$10
	stx     tmp1
	ora     tmp1
	jeq     L00FE
	ldx     #$00
	lda     #$5F
	sta     $0215
L00FE:	ldy     #$02
	ldx     #$00
	lda     (sp),y
	ldx     #$00
	and     #$80
	stx     tmp1
	ora     tmp1
	jeq     L0103
	ldx     #$00
	lda     #$5F
	sta     $0219
L0103:	ldy     #$02
	ldx     #$00
	lda     (sp),y
	ldx     #$00
	and     #$40
	stx     tmp1
	ora     tmp1
	jeq     L0108
	ldx     #$00
	lda     #$5F
	sta     $021D
L0108:	ldy     #$00
	jsr     _ReadJoystick1
	ldy     #$02
	sta     (sp),y
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jmp     L0110
L0110:	cmp     #$01
	jeq     L011F
	cmp     #$02
	jeq     L011B
	cmp     #$04
	jeq     L0117
	cmp     #$08
	jeq     L0113
	cmp     #$10
	jeq     L0127
	cmp     #$20
	jeq     L0123
	cmp     #$40
	jeq     L012F
	cmp     #$80
	jeq     L012B
	jmp     L0111
L0113:	lda     #<(_Effect41)
	ldx     #>(_Effect41)
	jsr     pushax
	jsr     _MusicEffect
	jmp     L0111
L0117:	lda     #<(_Effect42)
	ldx     #>(_Effect42)
	jsr     pushax
	jsr     _MusicEffect
	jmp     L0111
L011B:	lda     #<(_Effect43)
	ldx     #>(_Effect43)
	jsr     pushax
	jsr     _MusicEffect
	jmp     L0111
L011F:	lda     #<(_Effect45)
	ldx     #>(_Effect45)
	jsr     pushax
	jsr     _MusicEffect
	jmp     L0111
L0123:	lda     #<(_Effect46)
	ldx     #>(_Effect46)
	jsr     pushax
	jsr     _MusicEffect
	jmp     L0111
L0127:	lda     #<(_Effect44)
	ldx     #>(_Effect44)
	jsr     pushax
	jsr     _MusicEffect
	jmp     L0111
L012B:	lda     #<(_Effect49)
	ldx     #>(_Effect49)
	jsr     pushax
	jsr     _MusicEffect
	jmp     L0111
L012F:	lda     #<(_Effect48)
	ldx     #>(_Effect48)
	jsr     pushax
	jsr     _MusicEffect
	jmp     L0111
L0111:	jmp     L00D9
	ldy     #$03
	jsr     leavey
	rts

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp7
	ldy     #$00
	jsr     _InitLCD
	ldy     #$00
	jsr     _InstallVT03
	ldx     #$00
	lda     #$00
	jsr     pushax
	jsr     _InitVT03System
	lda     #<(_StandardNMI)
	ldx     #>(_StandardNMI)
	jsr     pushax
	lda     #<(_StandardIRQ)
	ldx     #>(_StandardIRQ)
	jsr     pushax
	jsr     _SetVectors
	ldy     #$00
	jsr     _MusicInitial
	lda     #<(_Music_IndexTable)
	ldx     #>(_Music_IndexTable)
	jsr     pushax
	jsr     _MusicSetup
	ldy     #$00
	jsr     _ClearSprBuffer
	ldy     #$00
	jsr     _ClearPaletteBuffer
	ldy     #$00
	jsr     _EnableNMI
	ldy     #$00
	jsr     _CheckGameCount
	ldy     #$00
	jsr     staxysp
	ldy     #$00
	jsr     _CloseScreenDisplay
	lda     #<(_PICTable+12)
	ldx     #>(_PICTable+12)
	jsr     pushax
	jsr     _InitScreen
	ldy     #$00
	jsr     _PatternUpdate
	ldy     #$00
	jsr     _WaitPatternUpdate
	ldy     #$00
	jsr     _DisableNMI
	ldx     #$00
	lda     #$00
	jsr     pushax
	jsr     _InitVT03System
	lda     #<(_nmi)
	ldx     #>(_nmi)
	jsr     pushax
	lda     #<(_irq)
	ldx     #>(_irq)
	jsr     pushax
	jsr     _SetVectors
	ldy     #$00
	jsr     _InitSystem
	ldy     #$00
	jsr     _InitPalette
	ldy     #$00
	jsr     _EnableNMI
	ldy     #$00
	jsr     _InitMenuSprite
	ldy     #$00
	jsr     _OpenScreenDisplay
	ldx     #$00
	lda     #$00
	ldy     #$02
	jsr     staxysp
	ldx     #$00
	lda     #$00
	ldy     #$04
	jsr     staxysp
	ldy     #$00
	jsr     _WaitSync
	ldy     #$00
	jsr     _ReadJoystick1
	ldy     #$06
	sta     (sp),y
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	cmp     #$C0
	jsr     booleq
	jeq     L003E
	ldy     #$00
	jsr     _TestSystem
L003E:	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	jsr     _DisplayPage
L0045:	jmp     L0048
L0047:	jmp     L0045
L0048:	ldy     #$00
	jsr     _MusicLoop
	stx     tmp1
	ora     tmp1
	jeq     L0049
	lda     #<(_midi02)
	ldx     #>(_midi02)
	jsr     pushax
	jsr     _MusicPlay
L0049:	ldy     #$00
	jsr     _ReadJoystick1
	ldy     #$06
	sta     (sp),y
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	jmp     L0050
L0050:	cmp     #$01
	jeq     L0090
	cmp     #$02
	jeq     L0085
	cmp     #$04
	jeq     L006A
	cmp     #$08
	jeq     L0053
	cmp     #$80
	jeq     L00A6
	jmp     L0051
L0053:	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	lda     #$01
	jsr     tosgea0
	jeq     L0054
	ldy     #$03
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     decax1
	ldy     #$02
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	lda     #<(_Effect43)
	ldx     #>(_Effect43)
	jsr     pushax
	jsr     _MusicEffect
	jmp     L005A
L0054:	ldy     #$05
	lda     (sp),y
	dey
	ora     (sp),y
	jeq     L005A
	ldx     #$00
	lda     #$11
	ldy     #$04
	jsr     subeqysp
	lda     #<(_Effect47)
	ldx     #>(_Effect47)
	jsr     pushax
	jsr     _MusicEffect
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	jsr     _DisplayPage
	ldx     #$00
	lda     #$10
	ldy     #$02
	jsr     staxysp
L005A:	ldy     #$03
	jsr     ldaxysp
	jsr     aslax3
	ldy     #$38
	jsr     incaxy
	sta     $0200
	jmp     L0051
L006A:	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	lda     #$10
	jsr     toslta0
	jeq     L006B
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     tosaddax
	jsr     incax1
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     tosltax
	jeq     L006D
	ldy     #$03
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$02
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
L006D:	lda     #<(_Effect43)
	ldx     #>(_Effect43)
	jsr     pushax
	jsr     _MusicEffect
	jmp     L0074
L006B:	ldy     #$05
	jsr     ldaxysp
	ldy     #$11
	jsr     incaxy
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     tosltax
	jeq     L0074
	ldy     #$04
	ldx     #$00
	lda     #$11
	jsr     addeqysp
	lda     #<(_Effect47)
	ldx     #>(_Effect47)
	jsr     pushax
	jsr     _MusicEffect
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	jsr     _DisplayPage
	ldx     #$00
	lda     #$00
	ldy     #$02
	jsr     staxysp
L0074:	ldy     #$03
	jsr     ldaxysp
	jsr     aslax3
	ldy     #$38
	jsr     incaxy
	sta     $0200
	jmp     L0051
L0085:	ldy     #$05
	lda     (sp),y
	dey
	ora     (sp),y
	jeq     L0086
	ldx     #$00
	lda     #$11
	ldy     #$04
	jsr     subeqysp
	lda     #<(_Effect47)
	ldx     #>(_Effect47)
	jsr     pushax
	jsr     _MusicEffect
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	jsr     _DisplayPage
L0086:	jmp     L0051
L0090:	ldy     #$05
	jsr     ldaxysp
	ldy     #$11
	jsr     incaxy
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     tosltax
	jeq     L0091
	ldy     #$04
	ldx     #$00
	lda     #$11
	jsr     addeqysp
L0096:	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     tosaddax
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     decax1
	jsr     tosgtax
	jeq     L0097
	ldy     #$03
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     decax1
	ldy     #$02
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	ldy     #$03
	jsr     ldaxysp
	jsr     aslax3
	ldy     #$38
	jsr     incaxy
	sta     $0200
	jmp     L0096
L0097:	lda     #<(_Effect47)
	ldx     #>(_Effect47)
	jsr     pushax
	jsr     _MusicEffect
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	jsr     _DisplayPage
L0091:	jmp     L0051
L00A6:	ldy     #$00
	jsr     _MusicInitial
	ldx     #$00
	lda     #$00
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     tosaddax
	jsr     aslax1
	clc
	adc     #<(_GamesDefine)
	tay
	txa
	adc     #>(_GamesDefine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	jsr     _RunGame
	jmp     L0051
L0051:	jmp     L0047
	ldx     #$00
	lda     #$01
	jmp     L0016
L0016:	jsr     incsp7
	rts

.endproc

