;
; File generated by cc65 v 2.10.1
;
	.fopt		compiler,"cc65 v 2.10.1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank, tmp1, ptr1, ptr2
	.macpack	longbranch
	.import		_InstallVT03
	.import		_InitVT03System
	.import		_WaitSync
	.import		_ClearSprBuffer
	.import		_InitScreen
	.import		_ClearPaletteBuffer
	.import		_PatternUpdate
	.import		_WaitPatternUpdate
	.import		_PaletteUpdate
	.import		_WaitPaletteUpdate
	.import		_EnableNMI
	.import		_OpenScreenDisplay
	.import		_OpenSpriteDisplay
	.import		_SetVectors
	.import		_StandardNMI
	.import		_StandardIRQ
	.import		_PICTable
	.import		_PALStepTable
	.import		_SpriteTable
	.export		_MainMenu
	.export		_ScreenStepin
	.import		_PALStepin
	.import		_GetPALSum
	.export		_DelayNMI
	.import		_InsertSprite
	.import		_InitSprite
	.import		_SetSprite
	.import		_SetSpriteXY
	.import		_ReadJoystick1
	.export		_main
	.import		_SpriteUpdate

; ---------------------------------------------------------------
; int __near__ MainMenu ()
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_MainMenu: near

.segment	"RODATA"

L0028:
	.byte	$45
	.byte	$5C
	.byte	$55
	.byte	$7C
	.byte	$55
	.byte	$9C
	.byte	$45
	.byte	$BC

.segment	"CODE"

	jsr     enter
	ldy     #$13
	jsr     subysp
	ldy     #$07
L0031:	lda     L0028,y
	sta     (sp),y
	dey
	bpl     L0031
	lda     #<(_PICTable+4)
	ldx     #>(_PICTable+4)
	jsr     pushax
	jsr     _InitScreen
	ldy     #$00
	jsr     _InitSprite
	ldx     #$00
	lda     #$20
	jsr     pushax
	ldx     #$00
	lda     #$17
	jsr     pushax
	lda     #<(_SpriteTable)
	ldx     #>(_SpriteTable)
	jsr     pushax
	jsr     _InsertSprite
	ldx     #$00
	lda     #$50
	jsr     pushax
	ldx     #$00
	lda     #$4F
	jsr     pushax
	lda     #<(_SpriteTable+4)
	ldx     #>(_SpriteTable+4)
	jsr     pushax
	jsr     _InsertSprite
	ldx     #$00
	lda     #$60
	jsr     pushax
	ldx     #$00
	lda     #$6F
	jsr     pushax
	lda     #<(_SpriteTable+4)
	ldx     #>(_SpriteTable+4)
	jsr     pushax
	jsr     _InsertSprite
	ldx     #$00
	lda     #$60
	jsr     pushax
	ldx     #$00
	lda     #$8F
	jsr     pushax
	lda     #<(_SpriteTable+4)
	ldx     #>(_SpriteTable+4)
	jsr     pushax
	jsr     _InsertSprite
	ldx     #$00
	lda     #$50
	jsr     pushax
	ldx     #$00
	lda     #$AF
	jsr     pushax
	lda     #<(_SpriteTable+4)
	ldx     #>(_SpriteTable+4)
	jsr     pushax
	jsr     _InsertSprite
	ldx     #$00
	lda     #$45
	jsr     pushax
	ldx     #$00
	lda     #$5C
	jsr     pushax
	lda     #<(_SpriteTable+8)
	ldx     #>(_SpriteTable+8)
	jsr     pushax
	jsr     _InsertSprite
	ldy     #$00
	jsr     _SpriteUpdate
	ldy     #$00
	jsr     _OpenSpriteDisplay
	ldy     #$00
	jsr     _PatternUpdate
	ldy     #$00
	jsr     _WaitPatternUpdate
	ldx     #$00
	lda     #$00
	ldy     #$0F
	jsr     staxysp
	ldx     #$00
	lda     #$00
	ldy     #$0D
	jsr     staxysp
	ldx     #$00
	lda     #$00
	ldy     #$0B
	jsr     staxysp
	ldx     #$00
	lda     #$00
	ldy     #$08
	jsr     staxysp
L0060:	lda     #<(_PALStepTable+4)
	ldx     #>(_PALStepTable+4)
	jsr     pushax
	ldy     #$12
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$11
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	jsr     pushax
	jsr     _PALStepin
	stx     tmp1
	ora     tmp1
	jeq     L0061
	ldy     #$00
	jsr     _PaletteUpdate
	ldy     #$00
	jsr     _WaitPaletteUpdate
	ldx     #$00
	lda     #$00
	ldy     #$11
	jsr     staxysp
L0068:	ldy     #$12
	jsr     ldaxysp
	jsr     pushax
	lda     #$04
	jsr     toslta0
	jne     L006B
	jmp     L0069
L006B:	ldy     #$00
	jsr     _WaitSync
	ldy     #$12
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$11
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	jmp     L0068
L0069:	ldy     #$0E
	jsr     ldaxysp
	jsr     incax2
	jsr     aslax2
	clc
	adc     #<(_PICTable)
	tay
	txa
	adc     #>(_PICTable)
	tax
	tya
	jsr     pushax
	jsr     _InitScreen
	ldy     #$0E
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$0D
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	ldy     #$0E
	jsr     ldaxysp
	ldx     #$00
	and     #$0F
	ldy     #$0D
	jsr     staxysp
	ldx     #$00
	lda     #$45
	jsr     pushax
	ldx     #$00
	lda     #$5C
	jsr     pushax
	ldx     #$00
	lda     #$05
	jsr     pushax
	ldy     #$12
	jsr     ldaxysp
	jsr     incax2
	jsr     aslax2
	clc
	adc     #<(_SpriteTable)
	tay
	txa
	adc     #>(_SpriteTable)
	tax
	tya
	jsr     pushax
	jsr     _SetSprite
	ldy     #$0C
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$0B
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	ldy     #$0C
	jsr     ldaxysp
	ldx     #$00
	and     #$07
	ldy     #$0B
	jsr     staxysp
	jmp     L0060
L0061:	ldx     #$00
	lda     #$00
	ldy     #$11
	jsr     staxysp
L0082:	jmp     L0085
L0084:	jmp     L0082
L0085:	ldy     #$00
	jsr     _WaitSync
	ldy     #$12
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$11
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	ldy     #$00
	jsr     _ReadJoystick1
	ldy     #$0A
	sta     (sp),y
	ldy     #$0A
	ldx     #$00
	lda     (sp),y
	jmp     L008B
L008B:	cmp     #$01
	jeq     L00B2
	cmp     #$02
	jeq     L00B0
	cmp     #$04
	jeq     L009F
	cmp     #$08
	jeq     L008E
	cmp     #$80
	jeq     L00B4
	jmp     L008C
L008E:	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	lda     #$01
	jsr     tosgea0
	jeq     L008F
	ldy     #$09
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     decax1
	ldy     #$08
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	jmp     L0092
L008F:	ldx     #$00
	lda     #$03
	ldy     #$08
	jsr     staxysp
L0092:	ldy     #$09
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     sp
	tay
	txa
	adc     sp+1
	tax
	tya
	ldy     #$00
	jsr     ldauidx
	jsr     pushax
	ldy     #$0B
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #$02
	bcc     L009B
	inx
	clc
L009B:	adc     sp
	tay
	txa
	adc     sp+1
	tax
	tya
	ldy     #$01
	jsr     ldauidx
	jsr     pushax
	ldx     #$00
	lda     #$05
	jsr     pushax
	jsr     _SetSpriteXY
	jmp     L008C
L009F:	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	lda     #$03
	jsr     toslta0
	jeq     L00A0
	ldy     #$09
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$08
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	jmp     L00A3
L00A0:	ldx     #$00
	lda     #$00
	ldy     #$08
	jsr     staxysp
L00A3:	ldy     #$09
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     sp
	tay
	txa
	adc     sp+1
	tax
	tya
	ldy     #$00
	jsr     ldauidx
	jsr     pushax
	ldy     #$0B
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #$02
	bcc     L00AC
	inx
	clc
L00AC:	adc     sp
	tay
	txa
	adc     sp+1
	tax
	tya
	ldy     #$01
	jsr     ldauidx
	jsr     pushax
	ldx     #$00
	lda     #$05
	jsr     pushax
	jsr     _SetSpriteXY
	jmp     L008C
L00B0:	jmp     L008C
L00B2:	jmp     L008C
L00B4:	jmp     L008C
L008C:	ldy     #$12
	jsr     ldaxysp
	jsr     pushax
	lda     #$04
	jsr     tosgea0
	jeq     L00B5
	ldy     #$0E
	jsr     ldaxysp
	jsr     incax2
	jsr     aslax2
	clc
	adc     #<(_PICTable)
	tay
	txa
	adc     #>(_PICTable)
	tax
	tya
	jsr     pushax
	jsr     _InitScreen
	ldy     #$0E
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$0D
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	ldy     #$0E
	jsr     ldaxysp
	ldx     #$00
	and     #$0F
	ldy     #$0D
	jsr     staxysp
	ldy     #$09
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     sp
	tay
	txa
	adc     sp+1
	tax
	tya
	ldy     #$00
	jsr     ldauidx
	jsr     pushax
	ldy     #$0B
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #$02
	bcc     L00C3
	inx
	clc
L00C3:	adc     sp
	tay
	txa
	adc     sp+1
	tax
	tya
	ldy     #$01
	jsr     ldauidx
	jsr     pushax
	ldx     #$00
	lda     #$05
	jsr     pushax
	ldy     #$12
	jsr     ldaxysp
	jsr     incax2
	jsr     aslax2
	clc
	adc     #<(_SpriteTable)
	tay
	txa
	adc     #>(_SpriteTable)
	tax
	tya
	jsr     pushax
	jsr     _SetSprite
	ldy     #$0C
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$0B
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	ldy     #$0C
	jsr     ldaxysp
	ldx     #$00
	and     #$07
	ldy     #$0B
	jsr     staxysp
	ldx     #$00
	lda     #$00
	ldy     #$11
	jsr     staxysp
L00B5:	jmp     L0084
	ldx     #$00
	lda     #$01
	jmp     L0025
L0025:	ldy     #$13
	jsr     leavey
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ ScreenStepin (void*, int, int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_ScreenStepin: near

.segment	"CODE"

	jsr     decsp4
	ldy     #$05
	lda     (sp),y
	dey
	ora     (sp),y
	jeq     L00CF
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staxysp
L00D3:	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	jsr     _PALStepin
	stx     tmp1
	ora     tmp1
	jeq     L00D4
	ldy     #$01
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$00
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	ldy     #$00
	jsr     _PaletteUpdate
	ldy     #$00
	jsr     _WaitPaletteUpdate
	ldx     #$00
	lda     #$00
	ldy     #$02
	jsr     staxysp
L00DB:	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     tosltax
	jne     L00DE
	jmp     L00DC
L00DE:	ldy     #$00
	jsr     _WaitSync
	ldy     #$03
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$02
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	jmp     L00DB
L00DC:	jmp     L00D3
L00D4:	jmp     L00E9
L00CF:	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	jsr     _GetPALSum
	ldy     #$00
	jsr     staxysp
L00E8:	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	lda     #$01
	jsr     tosgea0
	jeq     L00E9
	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	jsr     _PALStepin
	ldy     #$00
	jsr     _PaletteUpdate
	ldy     #$00
	jsr     _WaitPaletteUpdate
	ldx     #$00
	lda     #$00
	ldy     #$02
	jsr     staxysp
L00F0:	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     tosltax
	jne     L00F3
	jmp     L00F1
L00F3:	ldy     #$00
	jsr     _WaitSync
	ldy     #$03
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$02
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	jmp     L00F0
L00F1:	ldy     #$01
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     decax1
	ldy     #$00
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	jmp     L00E8
L00E9:	ldy     #$0A
	jsr     addysp
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ DelayNMI (int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DelayNMI: near

.segment	"CODE"

	jsr     decsp2
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staxysp
L00FB:	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     tosltax
	jne     L00FE
	jmp     L00FC
L00FE:	ldy     #$00
	jsr     _WaitSync
	ldy     #$01
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$00
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	jmp     L00FB
L00FC:	jsr     incsp4
	rts

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldy     #$00
	jsr     _InstallVT03
	ldx     #$00
	lda     #$86
	jsr     pushax
	jsr     _InitVT03System
	lda     #<(_StandardNMI)
	ldx     #>(_StandardNMI)
	jsr     pushax
	lda     #<(_StandardIRQ)
	ldx     #>(_StandardIRQ)
	jsr     pushax
	jsr     _SetVectors
	ldy     #$00
	jsr     _ClearSprBuffer
	ldy     #$00
	jsr     _ClearPaletteBuffer
	lda     #<(_PICTable)
	ldx     #>(_PICTable)
	jsr     pushax
	jsr     _InitScreen
	cli
	ldy     #$00
	jsr     _EnableNMI
	ldy     #$00
	jsr     _PatternUpdate
	ldy     #$00
	jsr     _WaitPatternUpdate
	ldy     #$00
	jsr     _OpenScreenDisplay
	lda     #<(_PALStepTable)
	ldx     #>(_PALStepTable)
	jsr     pushax
	ldx     #$00
	lda     #$04
	jsr     pushax
	ldx     #$00
	lda     #$01
	jsr     pushax
	jsr     _ScreenStepin
	ldx     #$00
	lda     #$0A
	jsr     pushax
	jsr     _DelayNMI
	lda     #<(_PALStepTable)
	ldx     #>(_PALStepTable)
	jsr     pushax
	ldx     #$00
	lda     #$04
	jsr     pushax
	ldx     #$00
	lda     #$00
	jsr     pushax
	jsr     _ScreenStepin
	ldy     #$00
	jsr     _MainMenu
L0020:	jmp     L0023
L0022:	jmp     L0020
L0023:	jmp     L0022
	ldx     #$00
	lda     #$01
	jmp     L0002
L0002:	rts

.endproc

